#!/bin/sh
# Shell wrapper for R executable.

R_HOME_DIR=/home/faculty/hyu/R/R-1.4.1
R_HOME=${R_HOME_DIR}
export R_HOME

## NOTE:
## We must set this here rather than in the main binary.
: ${R_LD_LIBRARY_PATH=${R_HOME}/bin:/usr/local/lib:/usr/X11R6/lib:/usr/lib:/usr/lib:/usr/X11R6/lib:/usr/lib/gcc-lib/i386-redhat-linux/2.96:/usr/lib/gcc-lib/i386-redhat-linux/2.96/../../..}
if test -z "${LD_LIBRARY_PATH}"; then
  LD_LIBRARY_PATH="${R_LD_LIBRARY_PATH}"
else
  LD_LIBRARY_PATH="${R_LD_LIBRARY_PATH}:${LD_LIBRARY_PATH}"
fi
export LD_LIBRARY_PATH

args="--save -q"
while test -n "${1}"; do
  case ${1} in
    *)
      args="${args} ${1}" ;;
  esac
  shift
done

## R_HOME may have moved, so check
## (or you get "GUI X11 is not supported")
if test -x ${R_HOME}; then
  :
else
  echo "R_HOME (\`${R_HOME}') not found"
  exit 1
fi

## Startup
R_binary="R.bin"
  exec ${R_HOME}/bin/${R_binary}  ${args}
